### ISSUE TITLE
Describe the callflow for using these APIs

### ISSUE THREAD

**Issue by BenjaminBusvel** [camaraproject/WebRTC#18]
**Problem description**
It's not clear how to used these APIs

What is the rule of Registration and Connection Management
**Expected action**
Create some explanations or callflow to describe how to used it

**Comment by JavierVillaLabarra** [comment]
Hello Benjamin.

just PRed a proposal of the API flow you are requesting. [PR#21](https://github.com/camaraproject/WebRTC/pull/21)

feel free to provide comments!!
