### ISSUE TITLE
Why transactionId and clientId headers must be present on get session in OneToOneCall API 

### ISSUE THREAD

**Issue by BenjaminBusvel** [camaraproject/WebRTC#19]
**Problem description**
Why transactionId and clientId headers must be present on get session in OneToOneCall API 

**Expected behavior**
These fields must be populated at the POST session and can be returned in the post response with a sessionId in UUID format returned. For the get session only the sessionId returned at creation must be necessary

**Comment by pradeepachar-mavenir** [comment]
The transactionId is to track each of the requests made by the client. 
The clientId is an encoded value which shall be generated by encoding access-token or any other elements specific to the device. This shall enable the server to authenticate each and every requests made from the device.

**Comment by TEF-RicardoSerr** [comment]
Make sense to keep it as Pradeep was saying
