### ISSUE TITLE
BYON call handling (VVOIP) PUT lacks 200 OK JSON response body

### ISSUE THREAD

**Issue by deepakjaiswal1** [camaraproject/WebRTC#24]
@pradeepachar-mavenir  @TEF-RicardoSerr 
**Problem description**
The PUT method for BYON call handling does not return a JSON response body for successful requests (200 OK).

**Expected behavior**
The PUT method for BYON call handling needs to be updated to return a JSON response body for successful requests (200 OK). This response body should include relevant information about the updated call handling configuration.

**Comment by stroncoso-quobis** [comment]
Fully agree, PUT should return the body modified. Not empty body.

But I will go further, if we are talking about to modify a specific parameter of the session, won't be better to use PATCH? Using PUT we should include all session information, not just the parameters to change. This will allow to expand the API on the future, but just a suggestion.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH
> A PATCH request is considered a set of instructions on how to modify a resource. Contrast this with [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT); which is a complete representation of a resource.

**Comment by TEF-RicardoSerr** [comment]
This was fixed within last version of the API 0.1.2
