### ISSUE TITLE
Notifications Enhancement

### ISSUE THREAD

**Issue by TEF-RicardoSerr** [camaraproject/WebRTC#4]
As discussed in the meeting I open this issue in case Sushanth can provide any updates regarding the accomodation of Notifications in the proposed APIs which have already been PRed

**Comment by sushanthmavenir** [comment]
For Notifications, in the current API version, we have only considered websocket and the channel URL to be used for websocket establishment is included in the response to RACM API. In the near/far future when there is a need to support additional notification channels (e.g. PNS or Web hooks), there the current method will not work. Hence it is better to define a separate API to define the notification channel to be used, for the current version websocket will be the default, and extensible to support additional options in future versions. We will provide the yaml/json for notification api before the next meeting.

**Comment by eliaspc** [comment]
Maybe is better to rename the WebToken field to something not platform-dependent, as we expect to have support for non-web push notifications? Something like PushToken or simply Token. 

On the other hand, we suggest that all the required information about the caller is included in the body of the push notification, as mobile phones are not able to manage its content in some scenarios (eg Callkit in iOS).
