### ISSUE TITLE
Identity providing for users with multiple MSISDNs

### ISSUE THREAD

**Issue by TEF-RicardoSerr** [camaraproject/WebRTC#5]
Hello,
 
Reviewing the minutes of the meeting I have noticed that maybe there is a bit of misunderstanding within the client identity providing process. @deepakjaiswal1  commented that the current version of the API does not support choosing the line to be used for registration. It retrieves the MSISDN based on the deviceid provided by the client.  
 
Our vision is that, in cases where the user possesses multiple MSISDNs, the selection of the desired MSISDN does not depend on the API but rather on the IdP from the Telco. As the basic scenario for which this BYON API is intended is a device without a simcard or a webbrowser. The deviceId stands for the device where the BYON feature is being deployed. Then we consider that no further development of the API might be needed regarding this topic.
 
Are we all alligned on this?

**Comment by sushanthmavenir** [comment]
There are two topics here for discussion,
1 – Identity to be used for authentication and user profile retrieval from IDP. 
The RACM Request API has defined “userid” and “deviceId”. The deviceid is the unique device id while userid could be any Operator provided identity. Mavenir implementation previously used msisdn as userid, but we are ok to change this, if msisdn can be retrieved from the IDP. The key to be used for user profile retrieval from the IDP would be the SSO Access Token included in the RACM Request API (included as part of the Authorization header). 
We are aligned in principle for not sending MSISDN in the RACM API, but it would be good to discuss and align how this work end to end. 

2 – Line (aka MSISDN or Phone number) selection to be used for network registration. 
In line with my response to #1 above, our opinion here is to keep Line/MSISDN selection outside the communication API. The client must first be made aware of all the lines available for selection, and this comes under the provisioning scope. This should be done as part of the overall device management procedure, which can be separate API outside of the scope of comms API. From the dependency on IMS Registration, the WebRTC GW should support implicit registration of all the provisioned lines retrieved from the IDP. This avoids the client complexity for the Line to be explicitly registered and keeps the UX simple. Line selection will be required for call origination, and for this the existing Call API already has the parameter defined for capturing Originator’s address. In summary, our response is not to take this up into the RACM API.

**Comment by TEF-RicardoSerr** [comment]
Aligned with both cases.

1. We dont see the necessity to handle the MSISDN within the RACM API as long as you have the IdP Token. This way, maybe we need to figure out which parameter should be used instead or even whether it is not necessary to have the userID param and can be deleted. I also have a question regarding why is it important to have the deviceID param. I assume it is because there could be multiple webRTC devices that can be registered for the same user but if you can please clarify this... 
2. Agree. This should be done outside the API scope

**Comment by deepakjaiswal1** [comment]
I am in agreement with both cases and would like to offer a probable end to end flow for better clarity. In the context of the login process (following the login itself), there will be a user experience provided for selecting a line on a specific device, referred to as device-X. The user's selection will be stored in their user profile within the identity provider (iDP). The WebRTC Gateway will register lines that are designated as active or provisioned for device-X. It's important to note that the UserID can be omitted, but the device ID is essential. Our objective is to support a single registration for each device associated with a specific MSISDN. In the event of multiple registration requests from the same device, the previous registration should be cleared to enable re-login without a clean logout.

**Comment by eliaspc** [comment]
We should also clarify what we understand for "deviceID", specially when the users are using a browser where several tabs can be open at the same time. We can still provide "single registration" if we consider that each tab is a new deviceID (if this is a use case that we can to consider).

**Comment by deepakjaiswal1** [comment]
If we treat each browser tab as a distinct device, it could potentially lead to multiple registrations for the same browser. In such a scenario, if a user registers the same line on multiple tabs, it would result in multiple simultaneous rings for a single incoming call, causing confusion. To enhance the user experience, we've chosen to use the same deviceID for each tab when providing a similar service. This approach ensures that registration is limited to a single instance per browser, avoiding any such confusion.
