### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by TEF-RicardoSerr** [camaraproject/WebRTC#7]
Let me open this issue for Deepak (and anyone else that may want to contribute) to make a proposal with the Error examples that should be managed for this API

**Comment by deepakjaiswal1** [comment]
@TEF-RicardoSerr @sushanthmavenir @pradeepachar-mavenir
Here's our proposal for Create RACM Session error codes:

|status|---|code|--------------------------|message| 
|403|------|"MAX_REGISTRATION_PER_USER"|---|"The maximum number of service registrations per user has been reached"|
|403|------|"MAX_REGISTRATION_PER_MSISDN"|-|"The maximum number of service registrations per MSISDN has been reached"|
|403|------|"MAX_DEVICES_PER_USER"|--------|"The maximum number of device instances per user has been reached"|
|403|------|"EMERGENCY_ADDRESS_MISSING"|---|"Emergency address missing"|

**Comment by deepakjaiswal1** [comment]
@TEF-RicardoSerr I agree with you. Let's use 400 BR error for missing emergency address.

|400|------|"EMERGENCY_ADDRESS_MISSING"|---|"Emergency address missing"|
